#!/usr/bin/env bash

###############################################################################
# ERROR: Let the user know if the script fails
###############################################################################
# https://www.linuxjournal.com/content/bash-trap-command FOLLOW UP ON THIS

trap 'ret=$?; cmd=!0; test $ret -ne 0 && printf "\n   \e[31m\033[0m  Foundation failed  \e[31m\033[0m\nLast command:$cmd\n" >&2; exit $ret' EXIT

set -e

###############################################################################
# Apps, Brews, and Casks
###############################################################################

APPS=(
	1147396723::WhatsApp
)

BREWS=(
	bash
	coreutils
	bat
	exa
	git
	gh
	fzf
	less
	mas
	openssl@3
	tldr
	vim
	neovim
	tmux
	wget
	yarn
	fish
	zsh
	zsh-completions
	zsh-syntax-highlighting
	starship
)

CASKS=(
	arc
	brave-browser
	firefox
	google-chrome
	microsoft-edge
	vivaldi
	docker
	dropbox
	onedrive
	google-drive
	alacritty
	kitty
	spotify
	visual-studio-code
	microsoft-word
	microsoft-excel
	microsoft-powerpoint
	signal
	telegram
	zoom
)

###############################################################################
# TWIRL: Check for required functions file
###############################################################################

# Get arrays
APPS=$(curl -fs https://raw.githubusercontent.com/kellenproctor/foundation/master/swag/apps)
printf " "
DramaticTyping "Apps..." 0.1
PunnyCheck APPS "HOT AND FRESH!" "still in the freezer." "Ok to move ahead without apps?"

BREWS=$(curl -fs https://raw.githubusercontent.com/kellenproctor/foundation/master/swag/brews)
printf " "
DramaticTyping "Brews..." 0.1
PunnyCheck BREWS "COLD AND FOAMY!" "skunked" "Ok to move ahead without brews?"

CASKS=$(curl -fs https://raw.githubusercontent.com/kellenproctor/foundation/master/swag/casks)
printf " "
DramaticTyping "Casks..." 0.1
PunnyCheck CASKS "TAPPED AND FLOWING!" "not yet delivered" "OK to move ahead without casks?"

# Get twirl
eval "$(curl -s https://raw.githubusercontent.com/kellenproctor/foundation/master/twirl)"

if [ -v "$e_lemon_ated" ]; then
	printf "\n "
	DramaticTyping "Get ready for..." 0.1
	echo
	sleep 0.2
else
	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
	printf " Required functions file missing, please edit the script to get twirl\n"
	exit 1
fi

###############################################################################
# CHECK: Bash version
###############################################################################

check_bash_version

###############################################################################
# Get in Formation!          http://patorjk.com/software/taag/ ( font: Script )
###############################################################################

printf "
   _
  | |
  | |  __   ,_    _  _  _    __, _|_ 🍋  __   _  _
  |/  /  \_/  |  / |/ |/ |  /  |  |  |  /  \_/ |/ |
  |__/\__/    |_/  |  |  |_/\_/|_/|_/|_/\__/   |  |
  |\  ---------------------------------------------
  |/  Cause you slay           [for Bash 3.2 - 3.9]
╭───────────────────────────────────────────────────╮
│  Okay developers now let's get in ${bold}formation${normal}.      │
│───────────────────────────────────────────────────│
│  Safe to run multiple times on the same machine.  │
│  It ${green}installs${reset}, ${blue}upgrades${reset}, or ${yellow}skips${reset} packages based   │
│  on what is already installed on the machine.     │
╰───────────────────────────────────────────────────╯
   ${dim}$(get_os) $(get_os_version) ${normal} // ${dim}$BASH ${normal} // ${dim}$BASH_VERSION${reset}
"

sleep 0.2


###############################################################################
# CHECK: Internet
###############################################################################
chapter "Checking internet connection…"
check_internet_connection

###############################################################################
# PROMPT: Password
###############################################################################
chapter "Caching password…"
ask_for_sudo

###############################################################################
# PROMPT: SSH Key
###############################################################################
chapter "Checking for SSH key…"
ssh_key_setup

###############################################################################
# INSTALL: Dependencies
###############################################################################
chapter "Installing Dependencies…"

# -----------------------------------------------------------------------------
# XCode
# -----------------------------------------------------------------------------
if type xcode-select &>- && xpath=$( xcode-select --print-path ) &&
	test -d "${xpath}" && test -x "${xpath}" ; then
	print_success_muted "Xcode already installed. Skipping."
else
	step "Installing Xcode…"
	xcode-select --install
	print_success "Xcode installed!"
fi

if [ ! -d "$HOME/.bin/" ]; then
	mkdir "$HOME/.bin"
fi

# -----------------------------------------------------------------------------
# Bash-it
# -----------------------------------------------------------------------------
# if [ -d "$HOME/.bash_it" ]; then
# 	print_success_muted "Bash-it already installed. Skipping."
# else
# 	step "Installing Bash-it…"
# 	git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
# 	~/.bash_it/install.sh --silent --no-modify-config
# 	print_success "Bash-it installed!"
# fi

# -----------------------------------------------------------------------------
# NVM
# -----------------------------------------------------------------------------
if [ -x nvm ]; then
	step "Installing NVM…"
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
	print_success "NVM installed!"
	step "Installing latest Node…"
	nvm install node
	nvm use node
	nvm run node --version
	node -v && npm -v
	nodev=$(node -v)
	print_success "Using Node $nodev!"
else
	print_success_muted "NVM/Node already installed. Skipping."
fi

# -----------------------------------------------------------------------------
# Homebrew
# -----------------------------------------------------------------------------
if ! [ -x "$(command -v brew)" ]; then
	step "Installing Homebrew…"
	NONINTERACTIVE=1 /bin/bash -c \
	"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	# Need to change this depending on ARM or Linux !!!!!!!
	# export PATH="/usr/local/bin:$PATH" # Old Linux
	export PATH="/opt/homebrew/bin:$PATH"
	print_success "Homebrew installed!"
else
	print_success_muted "Homebrew already installed. Skipping."
fi

if brew list | grep -Fq brew-cask; then
	step "Uninstalling old Homebrew-Cask…"
	brew uninstall --force brew-cask
	print_success "Homebrew-Cask uninstalled!"
fi

###############################################################################
# UPDATE: Homebrew
###############################################################################
chapter "Updating Homebrew formulae…"
brew update -fv
brew bundle install -v 2>&1
exit_code=$?
if [ $exit_code -ne 0 ]; then
	print_warning "Skipping forward"
fi

###############################################################################
# INSTALL: brews
###############################################################################
if [ -z "${BREWS}" ]; then
	chapter "Installing Homebrew formulae…"

	for brew in $(BREWS); do
		install_brews $brew
	done
fi

###############################################################################
# INSTALL: casks
###############################################################################
chapter "Installing apps via Homebrew…"

for cask in ${CASKS}; do
	install_application_via_brew $cask
done

###############################################################################
# INSTALL: Mac App Store Apps
###############################################################################
chapter "Installing apps from App Store…"
if [ -x mas ]; then
	print_warning "Please install mas-cli first: brew mas. Skipping."
fi


if mas_setup; then
	# Workaround for associative array in Bash 3
	# https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
	for app in ${APPS}; do
		KEY="${app%%::*}"
		VALUE="${app##*::}"
		install_application_via_app_store $KEY $VALUE
	done
else
	print_warning "Please signin to App Store first. Skipping."
fi


###############################################################################
# CLEAN: Homebrew files
###############################################################################
chapter "Cleaning up Homebrew files…"
brew cleanup 2> /dev/null

###############################################################################
# INSTALL: npm packages
###############################################################################
# if [ -e $cwd/swag/npm ]; then
# 	chapter "Installing npm packages…"

# 	for pkg in $(<$cwd/swag/npm); do
# 		KEY="${pkg%%::*}"
# 		VALUE="${pkg##*::}"
# 		install_npm_packages $KEY $VALUE
# 	done
# fi

###############################################################################
# INSTALL: Chezmoi Dotfiles
###############################################################################
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --one-shot kellenproctor


###############################################################################
# OPTIONAL: Customizations
###############################################################################
chapter "Adding hot sauce…"

NERDFONTS_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/ryanoasis/nerd-fonts/releases/latest)
NERDFONTS_VERSION=$(get_github_version $NERDFONTS_RELEASE)

DIRECTORIES=(
    $HOME/Desktop/code
    $HOME/Desktop/design
    $HOME/Desktop/*dump
    $HOME/Desktop/GIFs
    $HOME/Desktop/projects
    $HOME/Desktop/screenshots
)

NERDFONTS=(
    CascadiaCode
    FiraCode
    SpaceMono
    Hack
    AnonymousPro
    Inconsolata
)

step "Making directories…"
for dir in ${DIRECTORIES[@]}; do
    mkd $dir
done

step "Installing fonts…"
for font in ${NERDFONTS[@]}; do
    if [ ! -d ~/Library/Fonts/$font ]; then
        printf "${indent}  [↓] $font "
        wget -P ~/Library/Fonts https://github.com/ryanoasis/nerd-fonts/releases/download/$NERDFONTS_VERSION/$font.zip --quiet
        unzip -q ~/Library/Fonts/$font -d ~/Library/Fonts/$font
        rm ~/Library/Fonts/$font
        print_in_green "${bold}✓ done!${normal}\n"
    else
        print_muted "${indent}✓ $font already installed. Skipped."
    fi
done

if [ -n $HOTSAUCE ]; then
	if ask "Do you want to add hot sauce?" Y; then
		eval $HOTSAUCE; printf "\n  You got hot sauce in your bag. 🔥 ${bold}Swag.${normal}\n";
	else
		print_success_muted "Hot sauce declined. Skipped.";
	fi
else
	print_warning "No hot-sauce found. Skipping."
fi


###############################################################################
# 🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋🍋
###############################################################################
e_lemon_ated
